# Questions targeted at the Stanford CS229 Machine Learning lectures in rag/Data/
SAMPLE_QUERIES = [
    "what is supervised learning according to the lecture",
    "explain how gradient descent works in linear regression",
    "what is the normal equation and when is it used",
    "what is overfitting and how does regularization help",
    "explain the perceptron learning algorithm",
    "what is logistic regression used for",
    "describe the Gaussian Discriminant Analysis algorithm",
    "what is the Naive Bayes classifier and what assumption does it make",
    "explain the kernel trick in support vector machines",
    "what is the bias-variance tradeoff",
    "describe the EM algorithm for Gaussian mixture models",
    "how does Principal Component Analysis reduce dimensionality",
    "what is k-means clustering and how does it work",
    "explain how decision trees split features",
    "what is reinforcement learning and how does it differ from supervised learning",
    "describe Markov Decision Processes",
    "what is value iteration in reinforcement learning",
    "explain backpropagation in neural networks",
    "what is cross-validation and why is it important",
    "describe the VC dimension and learning theory",
]
